# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 22:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gazzola', '0002_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gazzola.Topping')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='storeroom',
            name='count',
        ),
        migrations.RemoveField(
            model_name='storeroom',
            name='toppings',
        ),
        migrations.AddField(
            model_name='storeroom',
            name='storage',
            field=models.ManyToManyField(to='gazzola.Storage'),
        ),
    ]
