# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gazzola', '0003_auto_20161105_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='pizza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gazzola.Pizza'),
        ),
    ]
