# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazzola', '0005_auto_20161111_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pizza',
        ),
        migrations.AddField(
            model_name='order',
            name='pizzas',
            field=models.ManyToManyField(to='gazzola.OrderedPizza'),
        ),
        migrations.AddField(
            model_name='orderedpizza',
            name='pizza_name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
