# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazzola', '0006_auto_20161114_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=6),
        ),
    ]
