# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gazzola', '0007_auto_20161116_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gazzola.Review'),
        ),
    ]
